baseURL = "https://xayan.nu/"
title = "xayan.nu"
languageCode = "en-us"
defaultContentLanguage = "en-gb"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[menu]
[[menu.main]]
pageRef = "/"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
pageRef = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[outputs]
home = ["html", "rss"]
page = ["html"]
rss = ["rss"]
section = ["html", "rss"]
taxonomy = ["html", "rss"]
term = ["html", "rss"]

[module]
workspace = "xayan-nu.work"

[[module.imports]]
path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
sitename = "xayan.nu"
defaultColor = "dark"
additionalScripts = ["js/umami.js"]
mainSections = ["posts"]

[params.author]
intro = "xayan.nu"
name = "Xayan"
description = "There are no stupid questions, only stupid people."

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
