baseURL = "https://xayan.nu/"
title = "xayan.nu"
languageCode = "en-us"
defaultContentLanguage = "en-gb"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error", "warning-goldmark-raw-html"]
[menu]

[[menu.main]]
pageRef = "/"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
pageRef = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
pageRef = "categories"
name = "Categories"
url = "/categories/"
weight = 30

[outputs]

home = ["html", "rss"]
page = ["html"]
rss = ["rss"]
section = ["html"]
taxonomy = ["html"]
term = ["html"]

[module]

workspace = "xayan-nu.work"

[[module.imports]]
path = "github.com/hugo-sid/hugo-blog-awesome"

[params]

sitename = "xayan.nu"
description = "There are no stupid questions, only stupid people."
defaultColor = "dark"
toc = true
goToTop = true
additionalScripts = ["js/pikachu.js"]
mainSections = ["posts"]

[params.author]
intro = "xayan.nu"
name = "Xayan"
description = "There are no stupid questions, only stupid people."

[[params.socialIcons]]
name = "github"
url = "https://github.com/Xayan/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/xayan__"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
